### ISSUE TITLE
esphome+TTBO T-Display: no screen refresh

### ISSUE THREAD

**Issue by busqui04** [musk95/esphome#1]
**Operating environment/Installation:**

Raspberry Pi3B+
Hass.IO
Home Assistant 0.107.7
ESPHome 1.14.3

ESP32, TTGO T-Display

**Affected component:**
ESP32, TTGO T-Display

**Description of problem:**
The information on the display becomes overwritten on every update of the sensors. This is my current .yaml code:

`spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19
font:
  - file: "SFNSRounded.ttf"
    id: font_cs
    size: 40
sensor:
  - platform: homeassistant
    entity_id: sensor.sonda_ph_aquari
    id: ph_aqua
    internal: true
  - platform: homeassistant
    entity_id: sensor.temperatura_aquari
    id: temp_aqua
    internal: true
display:
  - platform: st7789v
    id: st7789vdisplay
    reset_pin: GPIO23
    dc_pin: GPIO16
    cs_pin: GPIO5
    bl_pin: GPIO4
    rotation: 90°
    brightness: 75%
    update_interval: 1s
    lambda: |-
      if (id(ph_aqua).has_state()) {
        it.printf(55, 10, id(font_cs), 0xF800, "%.1f °C", id(temp_aqua).state);
        it.printf(55, 60, id(font_cs), 0x7E0, "%.1f pH", id(ph_aqua).state);
      }`

**Comment by kbmetz** [comment]
I have the same issue as well. Also there does not appear to be any way to turn off the display

**Comment by busqui04** [comment]
This issue is already fixed. This is a wrong library code. You can find the solution on this link:

[https://community.home-assistant.io/t/esphome-ttgo-t-display-no-screen-refresh/183025](url)

**Comment by kbmetz** [comment]
Thank you! 

How do you turn the display off?

**Comment by busqui04** [comment]
You can try:
`lambda: |-
      // Turn the whole display on.
      it.fill(COLOR_ON);
      // Turn the whole display off.
      it.fill(COLOR_OFF);`

You can replace COLOR_OFF by 0x0000 (black)

**Comment by kbmetz** [comment]
That does not turn the display off. You can still see that its on looking at the side and it consumes power
